### ISSUE TITLE
Count not determine a constructor for the tag '!vault'

### ISSUE THREAD

**Issue by emsecrist** [thegeeklab/ansible-later#112]
Seeing the following linter error. According to the documentation, the yaml code is correct, so this looks like a bug in the linter.
```
ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... roles/base/tasks/xxx.yml:13: syntax error: could not determine a constructor for the tag '!vault'
```

yaml snippet:
```vars:
    password: !vault |  

      $VAULT STUFF
       ...
```
Running:
ansible-later 0.4.1
ansible-2.10.7
ansible-base-2.10.7

**Comment by xoxys** [comment]
Thanks for your report! I've already created a PR that will fix this issue. I'll tag a bug fix release later today.

**Comment by emsecrist** [comment]
Thanks for the quick help @xoxys !
