### ISSUE TITLE
Better rules for debug module

### ISSUE THREAD

**Issue by bbaassssiiee** [thegeeklab/ansible-later#228]
A quick debug task is quite common, but it does not have a name and often string notation is handy.

```yaml
    - debug: var=hostvars[inventory_hostname]
```

Would it be possible to have a rule where we can configure some things?

- debug should be absent/may be present
- debug may use string format/or strict YAML
- debug must be named/or not

**Comment by xoxys** [comment]
Not sure if I understand the requests. Debug tasks shouldnt be handled differently. The only difference in ansible-later right no is that it is not enforced to name it.

**Comment by bbaassssiiee** [comment]
`CheckNativeYaml` could have an exclude for debug.
