### ISSUE TITLE
logging level has no effect on this output

### ISSUE THREAD

**Issue by bbaassssiiee** [thegeeklab/ansible-later#252]
This is always printed whatever I configure:

```yaml
INFO: Meta meta/main.yml declares standards version 0.2
INFO: Handler handlers/main.yml declares standards version 0.2
INFO: RoleVars defaults/main.yml declares standards version 0.2
INFO: Task tasks/main.yml declares standards version 0.2
```

**Comment by bbaassssiiee** [comment]
molecule 3.2.4 requires PyYAML<6,>=5.1, but you have pyyaml 6.0 which is incompatible.
molecule-vmware 0.3.6 requires pyyaml<6,>=5.1, but you have pyyaml 6.0 which is incompatible.
molecule-vagrant 0.6.3 requires pyyaml<6,>=5.1, but you have pyyaml 6.0 which is incompatible.
molecule-openstack 0.3 requires pyyaml<6,>=5.1, but you have pyyaml 6.0 which is incompatible.
molecule-gce 0.2 requires pyyaml<6,>=5.1, but you have pyyaml 6.0 which is incompatible.
molecule-ec2 0.3 requires pyyaml<6,>=5.1, but you have pyyaml 6.0 which is incompatible.
Successfully installed PyYAML-6.0 ansible-later-1.4.1 yamllint-1.26.3

**Comment by xoxys** [comment]
Don't hijack closed issues... and I have no idea what to do with the posted snippet without context.
