### ISSUE TITLE
CheckScmInSrc failed for requirements.txt w/ scm+url schema

### ISSUE THREAD

**Issue by CarstenGrohmann** [thegeeklab/ansible-later#507]
Hi,

I've pinned the version of ansible-later in `requirements.txt` to a specific version. But this triggers an error, even if I think the line is correct. 

Interestingly, the test does not fail when I comment out the first line.

**Steps to reproduce:**
```
$ ll
total 4
-rw-r--r-- 1 carsten users 230 Dec 13 13:55 requirements.txt
$ cat requirements.txt 
ansible == 6.6.0
# use git version till fix for github.com/thegeeklab/ansible-later/issues/501
# is officially released in a version > 3.0.0
#ansible-later
git+https://github.com/thegeeklab/ansible-later@fa35fee#egg=ansible-later
$ ansible-later 
ERROR: [ANSIBLE0005] Standard 'Use `scm:` key rather than `src: scm+url`' not met:
... requirements.txt:5: syntax error: did not find expected <document start>
```

**First line commented out:**
```
$ cat requirements.txt 
#ansible == 6.6.0
# use git version till fix for github.com/thegeeklab/ansible-later/issues/501
# is officially released in a version > 3.0.0
#ansible-later
git+https://github.com/thegeeklab/ansible-later@fa35fee#egg=ansible-later
$ ansible-later 
```

Also, I would prefer to lower the severity from "Error" to "Warning" since this format is not a true bug/coding error.

Regards,
Carsten

**Comment by xoxys** [comment]
Hi, place your `requirements.txt` file outside the role or add it to the `exclude_files` list, see https://ansible-later.geekdocs.de/configuration/defaults/

The test is complaining about `syntax error: did not find expected <document start>` which is a yaml parse error due to the fact the file is not a valid yaml file. The file is detected by https://github.com/thegeeklab/ansible-later/blob/main/ansiblelater/candidate.py#L209 and this test is a bit broader to allow multiple valid yaml extensions e.g. `yml|yaml`.

**Comment by xoxys** [comment]
> Also, I would prefer to lower the severity from "Error" to "Warning" since this format is not a true bug/coding error.

That can be controlled by the user. For details, please read the `warning_filter` description at https://ansible-later.geekdocs.de/configuration/defaults/

**Comment by CarstenGrohmann** [comment]
I added an entry to `exclude_files` to solve this issue.

I am still struggling with the classification as a role file. I understand the attempt to parse as many yaml files as possible. With this approach, `requirements.txt` files are also classified as yaml files and each user has to manually exclude this Python default file. What do you think about blacklisting `requirements.txt` files to prevent them from being classified as `role files`, or excluding them automatically if the yaml parser fails?

**Comment by xoxys** [comment]
I thought about it again and think that your suggestion makes sense.
