### ISSUE TITLE
Add possibility to suppress missing version declaration

### ISSUE THREAD

**Issue by CarstenGrohmann** [thegeeklab/ansible-later#512]
We see a lot of schema warnings like:

```
WARNING: Template roles/role1/templates/proxy.xml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.2
```

since all of our roles don't contain meta information. That's our design decision. Currently we have 80 warnings and our Ansible project is still ongoing. 

Please provide an option to suppress that warnings at all.  I can just as well imagine a single warning like `"""WARNING: The project contains several artifacts without a declared standards version. Using latest standards version 0.2 for all. (call "ansible-later -v" to show all)"""`.

**Comment by xoxys** [comment]
As a quick fix, you can add the `version` parameter to the config file as described in https://ansible-later.geekdocs.de/configuration/defaults/

**Comment by CarstenGrohmann** [comment]
Your suggestion works fine for me. 

```
# cat .later.yml 
rules:
  version: "0.2"
```

Thank you

**Comment by xoxys** [comment]
Right now the version check is hard-coded but yes, I also had the idea to convert it to a rule instead.

**Comment by CarstenGrohmann** [comment]
That's great. I'll update our config once the new release is published.
