### ISSUE TITLE
Change output format to allow simple CI integration

### ISSUE THREAD

**Issue by CarstenGrohmann** [thegeeklab/ansible-later#516]
Hi,

we want to integrate ansible-later into our Jenkins pipeline to validate each merge request.

Currently, there is no parser for Jenkins for the current two-line output format. Please provide an option to change the output to a Pep8/[pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html#example-usage-and-output) or [Pylint](https://pylint.pycqa.org/en/latest/user_guide/usage/output.html) compatible format.

Thank you,
Carsten

**Comment by xoxys** [comment]
Hi, 

There is already a json logger that can be enabled via cli flag or config paramter that can be used for custom parsing.

**Comment by xoxys** [comment]
Small correction, it can be enabled via config file only right now.

**Comment by CarstenGrohmann** [comment]
Thank you for your fast response. We'll test to integrate the JSON output into Jenkins.
