### ISSUE TITLE
Consider a checks for lookup

### ISSUE THREAD

**Issue by CarstenGrohmann** [thegeeklab/ansible-later#530]
Hi,

What do you think about a check for lookup with this two sub-checks:

* `loop: lookup` without `wantlist=True`: should fail because `lookup` w/o `wantlist=True`  returns a string but `loop` requires a list
* `lookup(wantlist=True)` can be replaced by `query()`: to prevent issues with strings instead of lists in loops

?

More information: https://docs.ansible.com/ansible/latest/plugins/lookup.html#forcing-lookups-to-return-lists-query-and-wantlist-true

Regards,
Carsten

**Comment by xoxys** [comment]
Sounds reasonable, would you like to provide a PR?

**Comment by CarstenGrohmann** [comment]
I'm sorry, but I can't manage to work on a PR for it for the foreseeable future.

**Comment by xoxys** [comment]
`ansible-later` is discontinued now, please use `ansible-lint` instead.
