### ISSUE TITLE
Provide a possibility to skip single checks for single tasks

### ISSUE THREAD

**Issue by CarstenGrohmann** [thegeeklab/ansible-later#548]
Hi,

I've a single task to clear the shell history:

```
- name: Clear os history
  shell: "history -c"
  become: true
  become_user: "{{ myuser }}"
```

This causes two different errors:
```
ERROR: [ANSIBLE0010] Standard 'Shell should only be used when essential' not met:
... roles/myrole/tasks/main.yml:32: shell should only be used when piping, redirecting or chaining commands

ERROR: [ANSIBLE0011] Standard 'Commands should be idempotent' not met:
... roles/myrole/tasks/main.yml:32: commands should only read while using `changed_when` or try to be idempotent while using controls like `creates`, `removes` or `when`
```

Currently I just found how I can disable all checks for this task:
```
tags:
  - skip_ansible_later
```

But I would like to disable only these two error types for this one task. How is that possible?

Thank you,
Carsten

**Comment by xoxys** [comment]
Hi,

That's pretty complex to handle. Have you looked into [ansible-lint](https://ansible-lint.readthedocs.io) already? It provides a lot more features for complex environments and might fit your environment better?

**Comment by CarstenGrohmann** [comment]
Currently I can't use ansible-lint due to ansible/ansible-lint#2889.

**Comment by xoxys** [comment]
`ansible-later` is discontinued now, please use `ansible-lint` instead.
