### ISSUE TITLE
Document differences with other existing tools

### ISSUE THREAD

**Issue by ssbarnea** [thegeeklab/ansible-later#62]
I am happy to see others do take ansible content QA seriously and treat it as code. I think it would be great to explain

* what forking ansible-review was needed?
* why ansible-lint was not good enough?

As you probably know, I am the current maintainer of molecule and recently also taken ansible-lint under my wind and managed to make a pure community project, one that addresses previous stagnation issues. 

I am interesting in particular about problems, features, approaches that make ansible-later unique when compared with ansible-lint or ansible-review. Maybe it would be possible to join efforts and have a single linting tool that has multiple active maintainers? 

If I remember correctly, last time I checked with Will, ansible-review use-case became a bit obsoleted by newer versions of ansible-lint, which historically was the backendup of the review.  The idea that one could lint only the modified files on a git change does not really work in practice, for example a change in a file has big chances of breaking others files: removing or changing an ansible module could break an untouched playbook, that is just one case.

During 2020, I was able to implement a `--progressive` mode in ansible-lint, one that allows users to ignore errors already existing before current commit and only prevent regression of the quality (introduction of new violations). 

There are two other important features that are already on the 5.0 pre-release: making use of ansible syntax check and yamllint.

If it was not clear, ansible-lint would clearly welcome new core developers! ;)

**Comment by xoxys** [comment]
Thanks a lot for your report. First I agree that it might be useful to document the initial intention behind this fork. To be honest I don't remember the details :) back in time, the situation was a bit unclear and personally I was not really happy with the general way how ansible-review works. The changelog for v0.1.0 has some details about it https://github.com/thegeeklab/ansible-later/releases/tag/v0.1.0. As the future of ansible-lint/ansible-review wasn't really clear I had the impression, getting fixes and enhancements into ansible-review wouldn't be that simple. Besides that, I was starting to get into python development and maintaining and used this project as a good starting point.

A few months later ansible-lint has moved to the Ansible community, things started to change heavily and big progress was made during the last years and ansible-lint become the default linting tool, and it looks very promising. For sure, I'll take a closer look at ansible-lint again, but I couldn't be wrong to provide alternative tools for the same use case.

> If it was not clear, ansible-lint would clearly welcome new core developers! ;)

Sure, thanks ;)

**Comment by ssbarnea** [comment]
If you want, I can send you an invite to ansible-lint repo, and it would likely be enough if you watch what happens and maybe with triage.

**Comment by xoxys** [comment]
I would like to do so!

**Comment by ssbarnea** [comment]
Put a comment on https://github.com/ansible-community/ansible-lint/issues/815 for tracking history, you will see an invite soon.
