### ISSUE TITLE
 exclude_files: do not work

### ISSUE THREAD

**Issue by alexey-vostrikov** [thegeeklab/ansible-later#677]
It is a duplicate of #647

Please provide a minimal example repo to reproduce this issue.
https://github.com/alexey-vostrikov/ansible-later-bug-example

You can see that: .later.yml  contains
```
# Global settings for all defined rules
rules:
  # list of files to exclude
  exclude_files:
  - .gitlab-ci.yml
```

But if I run ansible-later in the root of my repo it fails with error

If I delete .gitlab-ci.yml then ansible-later runs smoothly

**Comment by xoxys** [comment]
Thanks. I was able to identify the issue now.
