### ISSUE TITLE
ANS108 - systemctl command used in place of systemd module

### ISSUE THREAD

**Issue by bataliero** [thegeeklab/ansible-later#838]
Hi

I those 2 examples below I see following error: 
ERROR: [ANS108] rule 'Commands should not be used in place of modules' not met

```
- name: Start graphical target 
  ansible.builtin.command:
    cmd: "systemctl isolate graphical.target"
```

```
- name: Set default system target to graphical 
  ansible.builtin.command:
    cmd: "systemctl set-default graphical.target"
```

However I do not see any module which could be used in place of "ansible.builtin.command"

Is there a workaround to suppress ANS108 only for those 2 tasks e.g, using # noqa: ANS108 inline?

Thanks!

**Comment by xoxys** [comment]
Hi, sorry, no this is not possible. You might want to give `ansible-lint` a try, as I plan to discontinue `ansible-later` soon.

**Comment by xoxys** [comment]
`ansible-later` is discontinued now, please use `ansible-lint` instead.
